  
version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: base
    container_name: server
    env_file:
      -  ./.env
    ports:
        - 80:80
    networks:
      - back-tier

    networks:
      back-tier: